"""empty message

Revision ID: 9aaeabadae08
Revises: 717f41821c03
Create Date: 2024-09-04 22:01:25.428251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaeabadae08'
down_revision: Union[str, None] = '717f41821c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
